language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
install:
- pip install six
- pip install motor
- pip install python-coveralls

services: mongodb
script: nosetests
after_success:
- coveralls
deploy:
  provider: pypi
  user: plasmashadow
  password:
    secure: pAcn6F8lBPUMUpPSDxTr20flRijyqTfvWI9tgr0+PSTT53kOY3fRiE6b6EOEMvNbw6Avt7VxYgBCE7Rk1wspDQw3Q+8wSwYUC8REN4E5OWOvRE9RrwNPkul6sM5yjz2PgwSTxg/KW/JHjodJK9hHEWe+BO9+IgNEyVCZcIE6f3c=
  on:
    branch: 'master'
